# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


cities = City.create([{:city => "San Francisco", :state => "California", :timezone => "Pacific"}, {:city => "New York", :state => "New York", :timezone => "Eastern"}, {:city => "Portland", :state => "Oregon", :timezone => "Pacific"}, {:city => "Chicago", :state => "Illinois", :timezone => "Central"}])

333.times do |i|
  Client.create([{:first_name => "Sam", :last_name => "Morrison", :bio => "Sam Morrison has been homeless for the past two years, shortly after he lost his job as a construction worker due to a back injury. His worker's comp did not cover his living expenses, forcing him out of his apartment and onto the street.", :location => "San Francisco", :special_notes => "Diabetic", :age => 54, :gender => "Male", :goals => "Get back on my feet", :picture => "http://www.photosbyiki.com/wp-content/uploads/galleries/post-60/63150002%20square.jpg"}, {:first_name => "Charles", :last_name => "Meyers", :bio => "Charles Meyers has been homeless for since March 2014, when he hit a major bout of depression. Turning to alcohol to dull the pain, he eventually dropped out of school and lost his job. He has since turned his life around, attending AA meetings and managing his clinical depression.", :location => "San Francisco", :special_notes => "Clinical depression, but taking medication", :age => 28, :gender => "Male", :goals => "Stay sober and go back to school.", :picture => "https://upload.wikimedia.org/wikipedia/commons/6/64/Alexei_on_the_streets_in_Prague.jpg"}, {:first_name => "Saundra", :last_name => "Williams", :bio => "Saundra Williams was in an abusive relationship for 12 years before she finally filed for divorce in January 2014. Her ex-husband does has failed to pay for child support, and as a single monther, she has not been able to find work that fits her hours.", :location => "San Francisco", :special_notes => "Victim of abuse. With two children.", :age => 34, :gender => "Female", :goals => "Provide to my children and regain my dignity.", :picture => "http://goodmenproject.com/wp-content/uploads/2013/07/Patricia.jpg"}])
end


1.times do |i|
   Client.create([{:first_name => "Sam", :last_name => "Morrison", :bio => "Sam Morrison has been homeless for the past two years, shortly after he lost his job as a construction worker due to a back injury. His worker's comp did not cover his living expenses, forcing him out of his apartment and onto the street.", :location => "Portland", :special_notes => "Diabetic", :age => 54, :gender => "Male", :goals => "Get back on my feet", :picture => "http://www.photosbyiki.com/wp-content/uploads/galleries/post-60/63150002%20square.jpg"}, {:first_name => "Charles", :last_name => "Meyers", :bio => "Charle Meyers has been homeless for since March 2014, when he hit a major bout of depression. Turning to alcohol to dull the pain, he eventually dropped out of school and lost his job. He has since turned his life around, attending AA meetings and managing his clinical depression.", :location => "Portland", :special_notes => "Clinical depression, but taking medication", :age => 28, :gender => "Male", :goals => "Stay sober and go back to school.", :picture => "http://www.janbanning.com/Gallery/DownOut/images/Down&Out%20Col%20SC_21-3300-9%20David%20Dr_Low_34.jpg"}, {:first_name => "Saundra", :last_name => "Williams", :bio => "Saundra Williams was in an abusive relationship for 12 years before she finally filed for divorce in January 2014. Her ex-husband does has failed to pay for child support, and as a single monther, she has not been able to find work that fits her hours.", :location => "Portland", :special_notes => "Victim of abuse. With two children.", :age => 34, :gender => "Female", :goals => "Provide to my children and regain my dignity.", :picture => "https://upload.wikimedia.org/wikipedia/commons/6/64/Alexei_on_the_streets_in_Prague.jpg"}])
 end

 555.times do |i|
   Client.create([{:first_name => "Sam", :last_name => "Morrison", :bio => "Sam Morrison has been homeless for the past two years, shortly after he lost his job as a construction worker due to a back injury. His worker's comp did not cover his living expenses, forcing him out of his apartment and onto the street.", :location => "Chicago", :special_notes => "Diabetic", :age => 54, :gender => "Male", :goals => "Get back on my feet", :picture => "http://www.photosbyiki.com/wp-content/uploads/galleries/post-60/63150002%20square.jpg"}, {:first_name => "Charles", :last_name => "Meyers", :bio => "Charle Meyers has been homeless for since March 2014, when he hit a major bout of depression. Turning to alcohol to dull the pain, he eventually dropped out of school and lost his job. He has since turned his life around, attending AA meetings and managing his clinical depression.", :location => "Chicago", :special_notes => "Clinical depression, but taking medication", :age => 28, :gender => "Male", :goals => "Stay sober and go back to school.", :picture => "http://www.janbanning.com/Gallery/DownOut/images/Down&Out%20Col%20SC_21-3300-9%20David%20Dr_Low_34.jpg"}, {:first_name => "Saundra", :last_name => "Williams", :bio => "Saundra Williams was in an abusive relationship for 12 years before she finally filed for divorce in January 2014. Her ex-husband does has failed to pay for child support, and as a single monther, she has not been able to find work that fits her hours.", :location => "Chicago", :special_notes => "Victim of abuse. With two children.", :age => 34, :gender => "Female", :goals => "Provide to my children and regain my dignity.", :picture => "http://goodmenproject.com/wp-content/uploads/2013/07/Patricia.jpg"}])
 end

  333.times do |i|
   Client.create([{:first_name => "Sam", :last_name => "Morrison", :bio => "Sam Morrison has been homeless for the past two years, shortly after he lost his job as a construction worker due to a back injury. His worker's comp did not cover his living expenses, forcing him out of his apartment and onto the street.", :location => "New York", :special_notes => "Diabetic", :age => 54, :gender => "Male", :goals => "Get back on my feet", :picture => "http://www.photosbyiki.com/wp-content/uploads/galleries/post-60/63150002%20square.jpg"}, {:first_name => "Charles", :last_name => "Meyers", :bio => "Charle Meyers has been homeless for since March 2014, when he hit a major bout of depression. Turning to alcohol to dull the pain, he eventually dropped out of school and lost his job. He has since turned his life around, attending AA meetings and managing his clinical depression.", :location => "New York", :special_notes => "Clinical depression, but taking medication", :age => 28, :gender => "Male", :goals => "Stay sober and go back to school.", :picture => "https://upload.wikimedia.org/wikipedia/commons/6/64/Alexei_on_the_streets_in_Prague.jpg"}, {:first_name => "Saundra", :last_name => "Williams", :bio => "Saundra Williams was in an abusive relationship for 12 years before she finally filed for divorce in January 2014. Her ex-husband does has failed to pay for child support, and as a single monther, she has not been able to find work that fits her hours.", :location => "New York", :special_notes => "Victim of abuse. With two children.", :age => 34, :gender => "Female", :goals => "Provide to my children and regain my dignity.", :picture => "http://goodmenproject.com/wp-content/uploads/2013/07/Patricia.jpg"}])
 end
